const Routes = {
  Splash: 'Splash',
  AuthStack: 'AuthStack',
  Login: 'Login',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  MainTab: 'MainTab',
  DashboardStack: 'DashboardStack',
  MessageStack: 'MessageStack',
  UpcomingStack: 'UpcomingStack',
  TutorStack: 'TutorStack',
  SettingStack: 'SettingStack',
  CourseStack: 'CourseStack',
  BecomeTutorStack: 'BecomeTutorStack',
  Dashboard: 'Dashboard',
  Tutors: 'Tutors',
  TutorDetail: 'TutorDetail',
  Courses: 'Courses',
  CourseDetail: 'CourseDetail',
  Messages: 'Messages',
  UpcomingSession: 'UpcomingSession',
  VideoConference: 'VideoConference',
  CompleteProfile: 'CompleteProfile',
  VideoIntro: 'VideoIntro',
  Approval: 'Approval',
  Settings: 'Settings',
  Profile: 'Profile',
  Feedbacks: 'Feedbacks',
  BookingHistory: 'BookingHistory',
  SessionHistory: 'SessionHistory',
  AdvancedSettings: 'AdvancedSettings',
  PDF: 'PDF',
};

export default Routes;
